### PR TITLE
fix: UnhandledPromiseRejection in ServiceObject test

### LINKED ISSUE #174: UnhandledPromiseRejection in ServiceObject test
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: darwin 17.6.0
  - Node.js version: v10.4.1
  - npm version: v6.1.0
  - @google-cloud/common version: a35bd97

#### Steps to reproduce

  1. npm run test

screen shot 2018-06-26 at 12 54 32 pm

### PR DESCRIPTION
**Pull request by kinwa91**
Fixes #174 

- [ ] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

File: test/service-object.ts [hunk 1]
```diff
@@ -550,12 +550,12 @@ describe('ServiceObject', () => {
...
             assert.strictEqual(reqOpts_.method, method.reqOpts.method);
             assert.deepEqual(reqOpts_.qs, method.reqOpts.qs);
-            done();
+            return {body: {}};
           });
 
       const serviceObject = new ServiceObject(CONFIG) as FakeServiceObject;
       serviceObject.methods.getMetadata = method;
-      serviceObject.getMetadata(() => {});
+      serviceObject.getMetadata(() => done());
```
Comment (JustinBeckwith) [inline test/service-object.ts]: you can just `serviceObject.getMetadata(done);` :)
