### PR TITLE
fix: correctly locate projectId from auth library

### LINKED ISSUE #936: keyFilename in BQ constructor is not enough to authenticate API calls
When a user instantiates a client with just a `keyFilename`, an error pops up saying that a project ID is required. 

So, for example: 
```
  const bigquery = new BigQuery({
    keyFilename:
      PATH_TO_KEYFILE,
  });
```

returns:
```
Error: Sorry, we cannot connect to Cloud Services without a project
 ID. You may specify one with an environment variable named
 "GOOGLE_CLOUD_PROJECT".
    at Object.replaceProjectIdToken (/Users/sofialeon/gcp/nodejs-bigquery/samples/node_modules/@google-cloud/projectify/build/src/index.js:46:19)
    at Util.decorateRequest (/Users/sofialeon/gcp/nodejs-bigquery/samples/node_modules/@google-cloud/common/build/src/util.js:484:36)
    at onAuthenticated (/Users/sofialeon/gcp/nodejs-bigquery/samples/node_modules/@google-cloud/common/build/src/util.js:335:53)
    at /Users/sofialeon/gcp/nodejs-bigquery/samples/node_modules/@google-cloud/common/build/src/util.js:381:21
```

In other client libraries, this should be a sufficient method for providing authentication. See [this bug](https://github.com/googleapis/google-auth-library-nodejs/issues/1084) for more details on the investigation.

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes https://github.com/googleapis/nodejs-bigquery/issues/936

Previously, the user's project ID was checked against a private property from `google-auth-library`: `_cachedProjectId`. This is not always set, including when a `keyFilename` argument is passed. I found a method from the auth library, `getProjectId()`, which will first search for, then return the most correct project ID.

### CODE REVIEW

File: src/util.ts [hunk 1]
```diff
@@ -598,7 +598,7 @@ export class Util {
       const callback =
         typeof optionsOrCallback === 'function' ? optionsOrCallback : undefined;
 
-      const onAuthenticated = (
+      const onAuthenticated = async (
```
Comment (JustinBeckwith) [inline src/util.ts:601]: It's a little suspicious that this was switched to an async method, but I don't see an `await` anywhere getting added.  Where is this function called from?

File: src/util.ts [hunk 2]
```diff
@@ -615,7 +615,7 @@ export class Util {
 
         if (!err || autoAuthFailed) {
           // eslint-disable-next-line @typescript-eslint/no-explicit-any
-          let projectId = (authClient as any)._cachedProjectId;
```
Comment (JustinBeckwith) [inline src/util.ts:618]: this would be a good time to get rid of the `as any` here, since that method should very much be public and exist on the types now

File: test/util.ts [hunk 3]
```diff
@@ -697,7 +697,9 @@ describe('common/util', () => {
   describe('makeAuthenticatedRequestFactory', () => {
     const authClient = {
       getCredentials() {},
-      _cachedProjectId: 'project-id',
+      getProjectId: () => {
```
Comment (JustinBeckwith) [inline test/util.ts:700]: Since this is async in the library, should it be an async function here?

File: src/util.ts (hunk 1 above)
Comment (stephenplusplus) [reply src/util.ts:601]: This was just to enable me to use an await inside to get the project ID, without using the whole promise/callback thing.

File: src/util.ts (hunk 2 above)
Comment (stephenplusplus) [reply src/util.ts:618]: Good call, done!

File: test/util.ts (hunk 3 above)
Comment (stephenplusplus) [reply test/util.ts]: Makes sense to me! Changed 👍🏻

File: src/util.ts (hunk 1 above)
Comment (JustinBeckwith) [reply src/util.ts:601]: Sure, but now when this method is called, it won't execute synchronously.  Where we invoke `onAuthenticated`, I would expect to now require an `await`?

Comment (stephenplusplus) [reply src/util.ts]: Sorry, that was definitely a mistake! I've made an update to consolidate some code and embrace the promise chain :)

**Comment by sofisl** [comment]
@stephenplusplus, excited to get this PR merged! Would you mind taking a look at some of our comments, excited to look over and merge soon.

File: src/util.ts [hunk 4]
```diff
@@ -614,17 +615,10 @@ export class Util {
...
-
-          if (config.projectId && config.projectId !== '{{projectId}}') {
-            projectId = config.projectId;
-          }
-
           try {
             authenticatedReqOpts = util.decorateRequest(
               authenticatedReqOpts!,
-              projectId
+              projectId!
```
[the remark this answers is not in the document]
Comment (stephenplusplus) [reply src/util.ts]: Sorry I missed this comment! I was able to remove the `!` in the last commit. PTAL and let me know if I overlooked anything. Thanks!

File: src/util.ts [hunk 5]
```diff
@@ -618,7 +618,7 @@ export class Util {
           try {
             authenticatedReqOpts = util.decorateRequest(
               authenticatedReqOpts!,
-              projectId!
+              projectId
```
Comment (stephenplusplus) [inline src/util.ts]: This code is inside of the callback function, `onAuthenticated`, executed after `authClient.getProjectId()`. That is when the `projectId` is assigned using what the authClient says is the correct project ID.

File: src/util.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (stephenplusplus) [reply src/util.ts]: Woops, I noticed I left an edge case out. Fix incoming!

[the remark this answers is not in the document]
Comment (stephenplusplus) [reply src/util.ts]: Woops, I noticed I left an edge case out. Fix incoming!

**Comment by tmatsuo** [comment]
What's remaining on this PR?

**Comment by stephenplusplus** [comment]
I think we just need a @sofisl review.

**Review by bcoe — APPROVED** [review]
